//
//  AttributeKey.h
//  ALayout
//
//  Created by Splendour Bell on 2017/4/19.
//  Copyright © 2017年 Splendour Bell. All rights reserved.
//

#ifndef AttributeKey_h
#define AttributeKey_h

#define _ValueKey(_key_) @#_key_
#define ValueKey(_key_) _ValueKey(_key_)

#define A_adjustViewBounds                  adjustViewBounds
#define A_alwaysBounceHorizontal            showsHorizontalScrollIndicator
#define A_alwaysBounceVertical              alwaysBounceVertical
#define A_angle                             angle
#define A_antialias                         antialias
#define A_aspectRatio                       aspectRatio
#define A_background                        background
#define A_bottom                            bottom
#define A_bottomLeftRadius                  bottomLeftRadius
#define A_bottomRightRadius                 bottomRightRadius
#define A_bounces                           bounces
#define A_clickable                         clickable
#define A_centerColor                       centerColor
#define A_centerX                           centerX
#define A_centerY                           centerY
#define A_children                          children
#define A_class                             class
#define A_clearButtonMode                   clearButtonMode
#define A_color                             color
#define A_corners                           corners
#define A_exclusiveTouch                    exclusiveTouch
#define A_dashGap                           dashGap
#define A_dashWidth                         dashWidth
#define A_dataBinder                        dataBinder
#define A_date                              date
#define A_datePickerMode                    datePickerMode
#define A_defaultImage                      defaultImage
#define A_directionalLockEnabled            directionalLockEnabled
#define A_divider                           divider
#define A_dividerPadding                    dividerPadding
#define A_drawable                          drawable
#define A_drawableBottom                    drawableBottom
#define A_drawableLeft                      drawableLeft
#define A_drawablePadding                   drawablePadding
#define A_drawableRight                     drawableRight
#define A_drawableTop                       drawableTop
#define A_editable                          editable
#define A_ellipsize                         ellipsize
#define A_enabled                           enabled
//#define A_onClick                           onClick
#define A_endColor                          endColor
#define A_estimatedRowHeight                estimatedRowHeight
#define A_estimatedSectionFooterHeight      estimatedSectionFooterHeight
#define A_estimatedSectionHeaderHeight      estimatedSectionHeaderHeight
#define A_gradient                          gradient
#define A_gradientRadius                    gradientRadius
#define A_gravity                           gravity
#define A_height                            height
#define A_hint                              hint
#define A_id                                id
#define A_ignoreGravity                     ignoreGravity
#define A_innerRadius                       innerRadius
#define A_innerRadiusRatio                  innerRadiusRatio
#define A_inset                             inset
#define A_insetLeft                         insetLeft
#define A_insetTop                          insetTop
#define A_insetRight                        insetRight
#define A_insetBotton                       insetBotton
#define A_inputType                         inputType
#define A_layout                            layout
#define A_layout_above                      layout_above
#define A_layout_alignBaseline              layout_alignBaseline
#define A_layout_alignBottom                layout_alignBottom
#define A_layout_alignEnd                   layout_alignEnd
#define A_layout_alignLeft                  layout_alignLeft
#define A_layout_alignParentBottom          layout_alignParentBottom
#define A_layout_alignParentEnd             layout_alignParentEnd
#define A_layout_alignParentLeft            layout_alignParentLeft
#define A_layout_alignParentRight           layout_alignParentRight
#define A_layout_alignParentStart           layout_alignParentStart
#define A_layout_alignParentTop             layout_alignParentTop
#define A_layout_alignRight                 layout_alignRight
#define A_layout_alignStart                 layout_alignStart
#define A_layout_alignTop                   layout_alignTop
#define A_layout_alignWithParentIfMissing   layout_alignWithParentIfMissing
#define A_layout_below                      layout_below
#define A_layout_centerHorizontal           layout_centerHorizontal
#define A_layout_centerInParent             layout_centerInParent
#define A_layout_centerVertical             layout_centerVertical
#define A_layout_gravity                    layout_gravity
#define A_layout_height                     layout_height
#define A_layout_margin                     layout_margin
#define A_layout_marginTop                  layout_marginTop
#define A_layout_marginLeft                 layout_marginLeft
#define A_layout_marginBottom               layout_marginBottom
#define A_layout_marginRight                layout_marginRight
#define A_layout_toLeftOf                   layout_toLeftOf
#define A_layout_toRightOf                  layout_toRightOf
#define A_layout_weight                     layout_weight
#define A_layout_width                      layout_width
#define A_layout_widthPercent               layout_widthPercent
#define A_left                              left
#define A_lines                             lines
#define A_lineSpacingExtra                  lineSpacingExtra
#define A_match_parent                      match_parent
#define A_maxHeight                         maxHeight
#define A_maximumDate                       maximumDate
#define A_maxLength                         maxLength
#define A_maxLines                          maxLines
#define A_maxWidth                          maxWidth
#define A_maxWidth                          maxWidth
#define A_measureWithLargestChild           measureWithLargestChild
#define A_minHeight                         minHeight
#define A_minimumDate                       minimumDate
#define A_minLines                          minLines
#define A_minWidth                          minWidth
#define A_minWidth                          minWidth
#define A_numberic                          numberic
#define A_onTintColor                       onTintColor
#define A_orientation                       orientation
#define A_padding                           padding
#define A_paddingTop                        paddingTop
#define A_paddingLeft                       paddingLeft
#define A_paddingBottom                     paddingBottom
#define A_paddingRight                      paddingRight
#define A_pagingEnabled                     pagingEnabled
#define A_password                          password
#define A_phoneNumber                       phoneNumber
#define A_radius                            radius
#define A_right                             right
#define A_rowGravity                        rowGravity
#define A_roundAsCircle                     roundAsCircle
#define A_scaleType                         scaleType
#define A_scrollEnabled                     scrollEnabled
#define A_shadow                            shadow
#define A_shadowColor                       shadowColor
#define A_shadowDx                          shadowDx
#define A_shadowDy                          shadowDy
#define A_shadowRadius                      shadowRadius
#define A_shadowOpacity                     shadowOpacity
#define A_shape                             shape
#define A_showDividers                      showDividers
#define A_showsHorizontalScrollIndicator    showsHorizontalScrollIndicator
#define A_showsVerticalScrollIndicator      showsVerticalScrollIndicator
#define A_size                              size
#define A_selected                          selected
#define A_on                                  on
#define A_separatorStyle                    separatorStyle
#define A_solid                             solid
#define A_src                               src
#define A_startColor                        startColor
#define A_state_enabled                     state_enabled
#define A_state_focused                     state_focused
#define A_state_pressed                     state_pressed
#define A_state_selected                    state_selected
#define A_stroke                            stroke
#define A_text                              text
#define A_textAlignment                     textAlignment
#define A_textColor                         textColor
#define A_textColorHighlight                textColorHighlight
#define A_textFieldClass                    textFieldClass
#define A_textSize                          textSize
#define A_textStyle                         textStyle
#define A_thickness                         thickness
#define A_thicknessRatio                    thicknessRatio
#define A_tileMode                          tileMode
#define A_tag                               tag
#define A_top                               top
#define A_topLeftRadius                     topLeftRadius
#define A_topRightRadius                    topRightRadius
#define A_typeface                          typeface
#define A_url                               url
#define A_useLevel                          useLevel
#define A_visibility                        visibility
#define A_ios_action                        action
#define A_weightSum                         weightSum
#define A_width                             width
#define A_wrap_content                      wrap_content

#if !__LP64__
#undef INT_MAX
#define INT_MAX (1<<30)
#endif
#endif /* AttributeKey_h */
